spring.application.name=Sistema de estacao meteorologica

# Common config
app.tenancy.default-tenant-id=public
app.iot.ingest.max-skew-seconds=300
app.cors.allow-credentials=false

# DynamoDB defaults
app.dynamodb.region=${AWS_REGION:us-east-1}
app.dynamodb.payload-reserved-keys=idEstacao,timestamp,tenant_id
app.dynamodb.payload-ignore-prefixes=

# Actuator
management.endpoints.web.exposure.include=health,info,refresh
management.endpoint.health.show-details=never
